=== brunoroeder/magento2_Correios/etc/package_dimension_limits.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dimension_limits" type="dimension_limitsType"/>
    <xs:complexType name="lenghtType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="min" use="optional"/>
                <xs:attribute type="xs:byte" name="max" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="widthType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="min" use="optional"/>
                <xs:attribute type="xs:byte" name="max" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="heightType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="min"/>
                <xs:attribute type="xs:byte" name="max"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="boxType">
        <xs:sequence>
            <xs:element type="lenghtType" name="lenght"/>
            <xs:element type="widthType" name="width"/>
            <xs:element type="heightType" name="height"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="envelopeType">
        <xs:sequence>
            <xs:element type="lenghtType" name="lenght"/>
            <xs:element type="widthType" name="width"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="diameterType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:byte" name="min"/>
                <xs:attribute type="xs:byte" name="max"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="rollType">
        <xs:sequence>
            <xs:element type="lenghtType" name="lenght"/>
            <xs:element type="diameterType" name="diameter"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dimension_limitsType">
        <xs:sequence>
            <xs:element type="boxType" name="box"/>
            <xs:element type="envelopeType" name="envelope"/>
            <xs:element type="rollType" name="roll"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== brunoroeder/magento2_Correios/etc/package_dimension_limits.xml
<?xml version="1.0" encoding="utf-8" ?>
<dimension_limits xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="package_dimension_limits.xsd">
    <box>
        <lenght min="16" max="105" />
        <width min="11" max="105" />
        <height min="2" max="30" />
    </box>
    <envelope>
        <lenght min="16" max="60" />
        <width min="11" max="60" />
    </envelope>
    <roll>
        <lenght min="18" max="105" />
        <diameter min="5" max="91" />
    </roll>
</dimension_limits>
